# Generated by Django 5.1.2 on 2024-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('numero_caixa', models.IntegerField(verbose_name='Número da caixa')),
            ],
        ),
    ]
