# Generated by Django 5.1.2 on 2024-10-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
    ]
